[package]
name = "fend"
# Don't forget to update print_version()
version = "0.1.14"
authors = ["printfn <printfn@users.noreply.github.com>"]
description = "Arbitrary-precision unit-aware calculator"
homepage = "https://github.com/printfn/fend"
repository = "https://github.com/printfn/fend"
readme = "README.md"
license = "MIT"
keywords = ["calculator", "cli", "conversion", "math", "tool"]
edition = "2018"
categories = ["command-line-utilities", "mathematics", "science"]

[dependencies]
rustyline = { version =  "8.0.0", default-features = false, package = "rustyline-with-hint-fix" }
directories = "3.0.1"
ctrlc = "3.1.8"

[dependencies.fend-core]
version = "0.1.14"
path = "../core"
